In [2]:
import pandas as pd
import glob
import matplotlib.pyplot as plt
import numpy as np

## filepath

In [2]:
#train_data = "../Switchboard-Corpus/swda_data/train_set.txt"
#test_data = "../Switchboard-Corpus/swda_data/test_set.txt"
#val_data = "../Switchboard-Corpus/swda_data/val_set.txt"

## 練習

In [1]:
swda_pass = "../Switchboard-Corpus/swda_data/"
dir_list = ["train", "test", "val"]

In [30]:
len(glob.glob(swda_pass + "train/*"))

1115

In [47]:
glob.glob(swda_pass + "train/*")[0]

'../Switchboard-Corpus/swda_data/train/2228.txt'

# 対話ルール設定

In [56]:
user_lists = []

utter_user = []
utter = []
utter_label = []

train_ = []
test_ = []
val_ = []

In [57]:
train_dataset = []
test_dataset = []
val_dataset = []

In [58]:
for j in dir_list:
    files_list = glob.glob(swda_pass + j + "/*")
    for file_name in files_list:
        print(file_name)
        f = open(file_name, "r", encoding='utf-8')
        l_train = []
        l_test = []
        l_val = []
        for row in f:
            if j == "train":
                l_train.append(row.strip())
            elif j == "test":
                l_test.append(row.strip())
            else:
                l_val.append(row.strip())
                
        if j == "train":
            train_dataset.append(l_train)
        elif j == "test":
            test_dataset.append(l_test)
        else:
            val_dataset.append(l_val)
        f.close()
        
print("finish")

../Switchboard-Corpus/swda_data/train/2228.txt
../Switchboard-Corpus/swda_data/train/3136.txt
../Switchboard-Corpus/swda_data/train/4659.txt
../Switchboard-Corpus/swda_data/train/2566.txt
../Switchboard-Corpus/swda_data/train/4103.txt
../Switchboard-Corpus/swda_data/train/2599.txt
../Switchboard-Corpus/swda_data/train/4856.txt
../Switchboard-Corpus/swda_data/train/3693.txt
../Switchboard-Corpus/swda_data/train/3320.txt
../Switchboard-Corpus/swda_data/train/4329.txt
../Switchboard-Corpus/swda_data/train/2994.txt
../Switchboard-Corpus/swda_data/train/3334.txt
../Switchboard-Corpus/swda_data/train/2770.txt
../Switchboard-Corpus/swda_data/train/3491.txt
../Switchboard-Corpus/swda_data/train/2957.txt
../Switchboard-Corpus/swda_data/train/3254.txt
../Switchboard-Corpus/swda_data/train/3526.txt
../Switchboard-Corpus/swda_data/train/2638.txt
../Switchboard-Corpus/swda_data/train/3268.txt
../Switchboard-Corpus/swda_data/train/2610.txt
../Switchboard-Corpus/swda_data/train/2604.txt
../Switchboar

In [59]:
len(train_dataset)

1115

In [60]:
train_utter_data = []
train_user_data = []
train_label_data = []
train_utter_datas = []
train_user_datas = []
train_label_datas = []
test = ""

In [89]:
utter_user = []
utter = []
utter_label = []

for j in train_dataset:
    l_label = []
    l_utter = []
    l_user = []
    for text in j:
        for i,v in enumerate(text.split("|")):
            if i == 0:
                l_user.append(v)
            elif i==1:
                l_utter.append(v)
            else:
                l_label.append(v)
    utter_user.append(l_user)
    utter.append(l_utter)
    utter_label.append(l_label)
print("finish")

finish


In [90]:
len(utter), len(utter_label), len(utter_user)

(1115, 1115, 1115)

In [91]:
utter_label[0][:10]

['fo_o_fw_"_by_bc', 'b', 'sd', 'sd', 'sd', 'sd', 'sd', 'b', 'bf', 'aa']

In [92]:
utter_user[0][:10]

['A', 'B', 'B', 'B', 'B', 'B', 'B', 'A', 'A', 'B']

In [96]:
train_utter_data = []
train_user_data = []
train_label_data = []
text = ""

for i,u in enumerate(utter_user):
    l_utter = []
    l_user = []
    l_label = []
    for j,v in enumerate(u):
        #print(v)
        if j == 0:
            text += utter[i][j] + " "
            continue
            
        if u[j-1] != v:
            l_label.append(utter_label[i][j-1])
            l_utter.append(text)
            l_user.append(u[j-1])
            text = ""
        
        text += utter[i][j] + " "
    train_utter_data.append(l_utter)
    train_label_data.append(l_label)
    train_user_data.append(l_user)
    
print("finish")

finish


In [97]:
len(train_label_data), len(train_user_data), len(train_utter_data)

(1115, 1115, 1115)

In [98]:
train_utter_data[0][:10], train_label_data[0][:10]

(['Okay. ',
  "All right, uh, feelings on what caused the S and L crisis I guess I don't have a real technical knowledge for what happened I gather that there where large numbers of situations where loans were made that appeared to be a good loan but in a speculative since and with have little regulation going on because of deregulation during the Reagan eight years, uh, more and more S and L simply began to take riskier and riskier loans and then when they began to collapse one after the other I think almost like an avalanche of, of property values devalued. ",
  "Uh-huh, kind of like a domino's effect. ",
  "Right. I don't have a, a field for whether or not this is the equivalent of what was called the teapot dome. Uh, scandal, ",
  'Oh, . ',
  'are you familiar with that, from your histories lessons or whatever. ',
  'No. No. ',
  "Uh, I vaguely recall but I've never gone and done any study on it since the S and L thing that teapot dome scandal is when I think during the Hoover year

In [114]:
train_utter_data = []
train_user_data = []
train_label_data = []
text = ""

for i,v in enumerate(utter_user):
    
    if utter_user[i-1] != v:
        #print("実行")
        train_user_data.append(utter_user[i-1])
        train_utter_data.append(text)
        train_label_data.append(utter_label[i-1])
        text = ""
        
    text += utter[i] + " "
    #print(text)

In [115]:
train_utter_data[:10]

["Have you ever gotten one of those calls that is either generated by a computer or somebody going down a list and their either offering a service or they're introducing some new product in the area and normally when they call, you're either in the shower, or you're in the middle of cooking something and you have to stop everything to run to the phone. ",
 "Yes, yes. Is, is that one that you're talking about. ",
 "That was the big one I'm talking about. I work weird hours, and invariably just about the time, I'm going to sleep, the phone tears off the wall. ",
 'Uh-huh, uh-huh. ',
 'And you are trying to crawl out of a half unconscious sleep and answer the phone, you either hear, the as soon as you say hello, you hear the click of the recording coming on, ',
 'Uh-huh. ',
 "or you hear somebody all ready starting, reading off a list of stuff that they've read probably a thousand times that day already. ",
 "That's true, or the ones that are, are generated by a computer. It's just a comp

In [116]:
train_label_data[:10]

['fo_o_fw_"_by_bc', 'qy', 'sd', 'b', 'sd', 'b', 'sd', 'sd', 'sd', 'sd']

In [117]:
train_user_data[:10]

['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A', 'B']

In [124]:
train_data = tf.data.Dataset.from_tensor_slices((train_utter_data[:-1], train_label_data[1:]))

In [128]:
i,v = next(iter(train_data))
print(i,v)

tf.Tensor(b"Have you ever gotten one of those calls that is either generated by a computer or somebody going down a list and their either offering a service or they're introducing some new product in the area and normally when they call, you're either in the shower, or you're in the middle of cooking something and you have to stop everything to run to the phone. ", shape=(), dtype=string) tf.Tensor(b'qy', shape=(), dtype=string)


In [11]:
labels = set(utter_label)
utter_labels = []
for i in utter_label:
    for j,v in enumerate(labels):
        if i == v:
            utter_labels.append(j)
        

In [8]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [12]:
train_data = tf.data.Dataset.from_tensor_slices((utter, utter_labels))

In [23]:
## ボキャブラリーリスト
vocabulary_set = set()
## トークナイザー
tokenizer = tfds.features.text.Tokenizer()

## 分かち書き
for text_tensor,_ in train_data:
    some_tokens = tokenizer.tokenize(text_tensor.numpy())
    vocabulary_set.update(some_tokens)
    
## ボキャブラリーリスト作成
vocab_size = len(vocabulary_set)

In [34]:
encoder = tfds.features.text.TokenTextEncoder(vocabulary_set)

In [63]:
def encode(token, label):
    token = encoder.encode(token.numpy())
    return token, label

@tf.function
def tf_encoder(utter, label):
    encoded_text, label = tf.py_function(encode,[utter, label],[tf.int64, tf.int32])
    encoded_text.set_shape([None])
    label.set_shape([])
    return encoded_text, label

"""
MAX_LENGTH = 10
def filter_max_length(x,y,max_length=MAX_LENGTH):
    return tf.logical_and(tf.size(x) <= max_length,
                        tf.size(y) <= max_length)
"""

'\nMAX_LENGTH = 10\ndef filter_max_length(x,y,max_length=MAX_LENGTH):\n    return tf.logical_and(tf.size(x) <= max_length,\n                        tf.size(y) <= max_length)\n'

In [46]:
train_data

<TensorSliceDataset shapes: ((), ()), types: (tf.string, tf.int32)>

In [54]:
all_train_data_encode = train_data.map(tf_encoder)

In [55]:
all_train_data_encode

<MapDataset shapes: ((None,), ()), types: (tf.int64, tf.int32)>

In [56]:
for i,v in all_train_data_encode.take(5):
    print(i,v)

tf.Tensor([276], shape=(1,), dtype=int64) tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(
[153 238 267 379 300 354 392 196 342 201 367  50 177 196 177 149 196 326
 285 196  60 369 354 336  95 169], shape=(26,), dtype=int64) tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(
[275 305 152 288 114 367 392 288 114 306 305  93 263 405  89  77  93  44
 367 139  71 364 354 201 367 392 368 288 114  94 367 392  24 367 392 226
 196  14 312 196 367 392  14 312 357 259], shape=(46,), dtype=int64) tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([106], shape=(1,), dtype=int64) tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([198], shape=(1,), dtype=int64) tf.Tensor(0, shape=(), dtype=int32)


In [57]:
all_train_data_encode = all_train_data_encode.filter(filter_max_length)

In [58]:
for i,v in all_train_data_encode.take(5):
    print(i,v)

tf.Tensor([276], shape=(1,), dtype=int64) tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([106], shape=(1,), dtype=int64) tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([198], shape=(1,), dtype=int64) tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([153 387], shape=(2,), dtype=int64) tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([ 26 228 125 136  77 336  95 169], shape=(8,), dtype=int64) tf.Tensor(6, shape=(), dtype=int32)


In [60]:
BATCH_SIZE = 64
max_len = 40

In [61]:
train_datasets = all_train_data_encode.padded_batch(64, padded_shapes=([max_len], []), drop_remainder=True)

In [75]:
train_batch, train_labels = next(iter(train_datasets))
train_batch.numpy()
train_batch.shape

TensorShape([64, 40])

In [69]:
emb = tf.keras.layers.Embedding(encoder.vocab_size, 64)

In [74]:
result = emb(train_batch)
result.shape

TensorShape([64, 40, 64])

In [7]:
train_dataset = []
f = open(train_data, "r", encoding='utf-8')
for row in f:
    train_dataset.append(row.strip())
f.close()

In [8]:
len(train_dataset)

192390

In [9]:
test_dataset = []
f = open(test_data, "r", encoding='utf-8')
for row in f:
    test_dataset.append(row.strip())
f.close()

In [10]:
len(test_dataset)

4078

In [11]:
val_dataset = []
f = open(val_data, "r", encoding='utf-8')
for row in f:
    val_dataset.append(row.strip())
f.close()

In [12]:
len(val_dataset)

3272

## データの分割

In [13]:
utter_user = []
utter = []
utter_label = []

In [14]:
train_dataset[0]
train_dataset[0].split("|")

['A', 'Okay.', 'fo_o_fw_"_by_bc']

In [15]:
for j in train_dataset:
    for i,v in enumerate(j.split("|")):
        if i == 0:
            utter_user.append(v)
        elif i==1:
            utter.append(v)
        else:
            utter_label.append(v)
print("finish")

finish


# 英語翻訳

## 蛇の目

In [132]:
pip install janome

Note: you may need to restart the kernel to use updated packages.


In [149]:
from janome.tokenizer import Tokenizer

## tensorflow

In [133]:
import tensorflow as tf
import tensorflow_datasets as tfds

## データの取り出し

In [193]:
en_utter = []
jp_utter = []
path = "./ch07/dataset/jpn.txt"

In [194]:
f = open(path, "r", encoding='utf-8')
text = ""
max_length = 0
count = 0
max_length_row = 0

for row in f:
    idx = row.find("_")
    if max_length < idx:
        max_length = idx
        max_length_row = count
    en_utter.append(row[:idx])
    jp_utter.append(row[idx+1:].split("\n")[0])
    count += 1

In [198]:
f.close()

## 配列をランダムに配置させる

In [211]:
import random
def rand_ints_nodup(a, b, k):
    ns = []
    while len(ns) < k:
        n = random.randint(a, b)
        if not n in ns:
            ns.append(n)
    return ns

random_lists = rand_ints_nodup(0, len(en_utter), 5000)

In [213]:
tests_list_jp = []
tests_list_en = []

for i in random_lists:
    tests_list_en.append(en_utter[i])
    tests_list_jp.append(jp_utter[i])

In [214]:
train_list_jp = []
train_list_en = []

for i in range(len(en_utter)):
    if i in random_lists:
        continue
        
    train_list_en.append(en_utter[i])
    train_list_jp.append(jp_utter[i])

In [215]:
len(train_list_en), len(tests_list_en)

(50639, 5000)

## トークナイザ

In [216]:
entokenizer = tfds.features.text.Tokenizer()
jptokenizer = Tokenizer(wakati=True)

In [217]:
inp_tokens, out_tokens = [], []
for i in en_utter:
    inp_tokens += entokenizer.tokenize(i)
for j in jp_utter:
    out_tokens += jptokenizer.tokenize(j)

In [243]:
len(inp_tokens)

378947

In [244]:
inp_vocab_lists = set(inp_tokens)
out_vocab_lists = set(out_tokens)

In [247]:
len(inp_vocab_lists)

10648

### ボキャブサイズ取得

In [219]:
inp_vocab_size = len(inp_vocab_lists)
out_vocab_size = len(out_vocab_lists)

In [220]:
tokenizaer_enutter = tfds.features.text.TokenTextEncoder(inp_vocab_lists)
tokenizaer_jputter = tfds.features.text.TokenTextEncoder(out_vocab_lists)

## データセットの用意

In [222]:
train_dataset = tf.data.Dataset.from_tensor_slices((train_list_en, train_list_jp))

In [223]:
test_dataset = tf.data.Dataset.from_tensor_slices((tests_list_en, tests_list_jp))

## パラメータ設定

In [224]:
BUFFER_SIZE = 50000
BATCH_SIZE = 64
TAKE_SIZE = 5000
MAX_LENGTH = 40
# 埋め込みベクトルの次元
embedding_dim = 256
# RNN ユニットの数
rnn_units = 1024

In [250]:
en_encoder = tfds.features.text.TokenTextEncoder(inp_vocab_lists)
jp_encoder = tfds.features.text.TokenTextEncoder(out_vocab_lists)

In [252]:
def encode(en,jp):
    en = en_encoder.encode(en.numpy())
    jp = jp_encoder.encode(jp.numpy())
    return en, jp

## 文の長さを固定

In [160]:
def filter_max_length(x, y, max_length=MAX_LENGTH):
    return tf.logical_and(tf.size(x) <= max_length,tf.size(y) <= max_length)

In [253]:
def tf_encoder(en, jp):
    return tf.py_function(encode, [en,jp], [tf.int64, tf.int64])

## データの中身確認

In [254]:
train_data = train_dataset.map(tf_encoder)
#train_data = train_data.filter(filter_max_length)
train_data = train_data.cache()
train_data = train_data.shuffle(BUFFER_SIZE).padded_batch(BATCH_SIZE, padded_shapes=([-1], [-1]))
train_data.prefetch(tf.data.experimental.AUTOTUNE)

<PrefetchDataset shapes: ((None, None), (None, None)), types: (tf.int64, tf.int64)>

In [255]:
example_input_batch, example_target_batch = next(iter(train_data))
example_input_batch.shape, example_target_batch.shape

(TensorShape([64, 13]), TensorShape([64, 2]))

In [256]:
sample_hidden.shape, example_input_batch.shape

(TensorShape([64, 1024]), TensorShape([64, 13]))

## モデル作成

## Encoder

In [257]:
class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
        super(Encoder, self).__init__()
        self.batch_sz = batch_sz
        self.enc_units = enc_units
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = tf.keras.layers.GRU(self.enc_units,
                                   return_sequences=True,
                                   return_state=True,
                                   recurrent_initializer='glorot_uniform')

    def call(self, x, hidden):
        x = self.embedding(x)
        output, state = self.gru(x, initial_state = hidden)
        return output, state

    def initialize_hidden_state(self):
        return tf.zeros((self.batch_sz, self.enc_units))

In [258]:
encoder = Encoder(inp_vocab_size, embedding_dim, rnn_units, BATCH_SIZE)
sample_hidden = encoder.initialize_hidden_state()
sample_output, sample_hidden = encoder(example_input_batch, sample_hidden)

In [259]:
print ('Encoder output shape: (batch size, sequence length, units) {}'.format(sample_output.shape))
print ('Encoder Hidden state shape: (batch size, units) {}'.format(sample_hidden.shape))

Encoder output shape: (batch size, sequence length, units) (64, 13, 1024)
Encoder Hidden state shape: (batch size, units) (64, 1024)


In [287]:
encoder.summary()

Model: "encoder_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     multiple                  2725888   
_________________________________________________________________
gru_7 (GRU)                  multiple                  3938304   
Total params: 6,664,192
Trainable params: 6,664,192
Non-trainable params: 0
_________________________________________________________________


## Decoder

In [285]:
class Decoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, dec_units, batch_sz):
        super(Decoder, self).__init__()
        self.batch_sz = batch_sz
        self.dec_units = dec_units
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = tf.keras.layers.GRU(self.dec_units,
                                   return_sequences=True,
                                   return_state=True,
                                   recurrent_initializer='glorot_uniform')
        self.fc = tf.keras.layers.Dense(vocab_size)
        
        
    def call(self, x, hidden):
        
        x = self.embedding(x)
        output, state = self.gru(x)
        output = tf.reshape(output, (-1, output.shape[2]))
        x = self.fc(output)
        return x, state

In [278]:
decoder = Decoder(out_vocab_size, embedding_dim, rnn_units, BATCH_SIZE)
sample_decoder_output, _ = decoder(tf.random.uniform((64, 1)), sample_hidden)

In [279]:
sample_decoder_output.shape

TensorShape([64, 14804])

In [288]:
decoder.summary()

Model: "decoder_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_16 (Embedding)     multiple                  3789824   
_________________________________________________________________
gru_12 (GRU)                 multiple                  3938304   
_________________________________________________________________
dense_11 (Dense)             multiple                  15174100  
Total params: 22,902,228
Trainable params: 22,902,228
Non-trainable params: 0
_________________________________________________________________


## オプティマイザと損失関数の定義

In [280]:
optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True, reduction='none')

def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    loss_ = loss_object(real, pred)

    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask

    return tf.reduce_mean(loss_)

## チェックポイント

In [282]:
import os

In [283]:
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(optimizer=optimizer,
                                 encoder=encoder,
                                 decoder=decoder)

## 訓練

In [284]:
@tf.function
def train_step(inp, targ, enc_hidden):
    loss = 0

    with tf.GradientTape() as tape:
        enc_output, enc_hidden = encoder(inp, enc_hidden)

        dec_hidden = enc_hidden

        dec_input = tf.expand_dims([targ_lang.word_index['<start>']] * BATCH_SIZE, 1)

    # Teacher Forcing - 正解値を次の入力として供給
    for t in range(1, targ.shape[1]):
      # passing enc_output to the decoder
        predictions, dec_hidden, _ = decoder(dec_input, dec_hidden, enc_output)

        loss += loss_function(targ[:, t], predictions)

      # Teacher Forcing を使用
        dec_input = tf.expand_dims(targ[:, t], 1)

    batch_loss = (loss / int(targ.shape[1]))

    variables = encoder.trainable_variables + decoder.trainable_variables

    gradients = tape.gradient(loss, variables)

    optimizer.apply_gradients(zip(gradients, variables))

    return batch_loss

In [ ]:
EPOCHS = 10

for epoch in range(EPOCHS):
    start = time.time()

    enc_hidden = encoder.initialize_hidden_state()
    total_loss = 0

    for (batch, (inp, targ)) in enumerate(train_data.take(steps_per_epoch)):
        batch_loss = train_step(inp, targ, enc_hidden)
        total_loss += batch_loss

        if batch % 100 == 0:
        print('Epoch {} Batch {} Loss {:.4f}'.format(epoch + 1,
                                                     batch,
                                                     batch_loss.numpy()))
  # 2 エポックごとにモデル（のチェックポイント）を保存
    if (epoch + 1) % 2 == 0:
        checkpoint.save(file_prefix = checkpoint_prefix)

    print('Epoch {} Loss {:.4f}'.format(epoch + 1,
                                      total_loss / steps_per_epoch))
    print('Time taken for 1 epoch {} sec\n'.format(time.time() - start))